### ISSUE TITLE
Issue with model identifiers when they aren't named "id"

### ISSUE THREAD

**Issue by adtrevor** [vapor/fluent-postgres-driver#123]
I'm not sure to understand exactly how `id` and `fluentID` are used by Fluent, but from what I can tell, in:
```swift
private struct PostgresReturning: SQLExpression {
    let base: SQLExpression
    init(_ base: SQLExpression) {
        self.base = base
    }

    func serialize(to serializer: inout SQLSerializer) {
        self.base.serialize(to: &serializer)
        serializer.write(#" RETURNING id as "fluentID""#)
    }
}
```

It doesn't seem ok to have `id` hardcoded in `RETURNING id as "fluentID"`, instead it should be the name of the primary key of the model, whatever it is.

What do you think?

**Comment by adtrevor** [comment]
The way I noticed this is that I got errors since my model identifiers aren't named `id`.

**Comment by Hejki** [comment]
Hi, I have same problem. It can be fixed if someone agree with [this changes](https://github.com/Hejki/fluent-kit/commit/5c45bb9af6f8e9aa6c3422e13d07c66745beb2bb) in fluent-kit.

Then `PostgresReturning` struct can be changed to
```swift
private struct PostgresReturning: SQLExpression {
    let base: SQLExpression
    let idKey: String

    init(_ base: SQLExpression, _ idKey: String) {
        self.base = base
        self.idKey = idKey
    }

    func serialize(to serializer: inout SQLSerializer) {
        self.base.serialize(to: &serializer)
        serializer.write(#" RETURNING "\#(idKey)" as "fluentID""#)
    }
}

// and change call initializer in _FluentPostgresDatabase extension
expression = PostgresReturning(expression, query.idKey)
```

**Comment by tanner0101** [comment]
Fixed. Thanks for reporting.
