### ISSUE TITLE
Add support for `~~` to work with array types

### ISSUE THREAD

**Issue by tonyarnold** [vapor/fluent-postgres-driver#126]
Given the following (incomplete) models:

```swift
final class OrganizationUser: PostgreSQLUUIDPivot {
    var roles: OrganizationUser.Roles = []

    typealias Roles = Set<Role>

    enum Role: Int, PostgreSQLRawEnum {
        case licenseManager = 1
        case billingManager = 2
        case owner = 3
    }
}
```

I would expect that I might be able to use one of the following:

```swift
query.filter(\OrganizationUser.roles ~~ .owner) // Type '[OrganizationUser.Roles]' (aka 'Array<Set<OrganizationUser.Role>>') has no member 'owner'

query.filter(\OrganizationUser.roles ~~ [.owner]) // Type 'OrganizationUser.Roles' (aka 'Set<OrganizationUser.Role>') has no member 'owner'
```

The following example works, but is nonsense - it produces a bogus equality query:

```swift
query.filter(\OrganizationUser.roles ~~ [[.owner]])
```

The only thing that currently works is:

```swift
query.filter(\OrganizationUser.roles, .contains, [.owner])
```

I apologise if this isn't the right repository. It seems specific to PostgreSQL's array implementation.

**Comment by tanner0101** [comment]
Fluent 4 now supports the `~~` on any type conforming to `Collection`.

**Comment by Flatout73** [comment]
@tanner0101 How to use it? `query.filter(\OrganizationUser.roles ~~ .owner)` is still not working:

`Binary operator '~~' cannot be applied to operands of type 'KeyPath<UniversityModel, FieldProperty<UniversityModel, [String]>>' and 'String'`

**Comment by 0xTim** [comment]
@Flatout73 contains needs an array to work so it should be `query.filter(\OrganizationUser.$roles ~~ [.owner])`

**Comment by 0xTim** [comment]
What type is `$tags`?

**Comment by Flatout73** [comment]
@0xTim

```
    @Field(key: "tags")
    var tags: [String]
```

**Comment by 0xTim** [comment]
@Flatout73 ah do you want to see if any of the tags match with `query`? That's more complicated and not something Fluent supports (because not all databases support it). You'll need to drop down to a custom filter and use something like https://stackoverflow.com/a/54069718/1823705

**Comment by Flatout73** [comment]
Yep, thank you, do you have example how to use custom filter? Is like this:
`.filter(.custom("<some sql>"))`

**Comment by tonyarnold** [comment]
@Flatout73 you can use it like this:

```swift
.filter(field, .custom("ilike"), "%\(queryString)%")
```

**Comment by Flatout73** [comment]
I have found solution:
`.filter(DatabaseQuery.Field.path(["tags"], schema: "universities"), .custom("&&"), DatabaseQuery.Value.custom("'{\"\(query)\"}'"))`

However, it will search if it is exact match, not just substring :(
