### ISSUE TITLE
updatedAt is incorrect after save

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/fluent-postgres-driver#146]
updatedAt Date is different after save and when we read it again.

### Steps to reproduce

My local time is 08:19, I am in +2 hours time zone

```swift
user.name = newName
user.save(on: request).do { user in
    // Here updated at is changed and has proper value
    // 2019-06-26 06:19:41 +0000
    print(user.updatedAt)
}.flatMap { user in
    // But when we read it again
    try User.find(user.requireID(), on: request).unwrap(or: Abort(.notFound))
}.do { user in
    // updatedAt is incorrect. Minus 2 hours from my real time
    // 2019-06-26 04:19:41 +0000
    print(user.updatedAt)
}
```

### Expected behavior

It should be the same after save and after reading again

### Actual behavior

updatedAt is incorrectly adjusted

### Environment

Package.resolved
https://github.com/vapor/vapor.git => 3.3.0
https://github.com/vapor/postgresql.git => 1.4.1

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: MacOS 10.14.5

**Comment by tanner0101** [comment]
Fixed by https://github.com/vapor/postgres-kit/pull/117
