### ISSUE TITLE
Accept URL string in configuration

### ISSUE THREAD

**Issue by joeyg** [vapor/fluent-postgres-driver#147]
When applying the [vapor 4.0 docs](https://docs.vapor.codes/4.0/fluent/overview/#postgresql
) to use a URL configuration a build error is produced.

For example using: `try app.databases.use(.postgres(url: databaseUrl), as: .psql)` instead of `app.databases.use(.postgres(hostname: "localhost", username: "vapor", password: "vapor", database: "vapor"), as: .psql)` creates the following error:
```
Sources/App/configure.swift:11:65: error: reference to member 'psql' cannot be resolved without a contextual type
        try app.databases.use(.postgres(url: databaseUrl), as: .psql)
```

**Comment by tanner0101** [comment]
I think you may need to convert `databaseUrl` to `Foundation.URL` first. We should probably have an overload for String there.

**Comment by joeyg** [comment]
That was it! Thanks!

**Comment by tanner0101** [comment]
This overload exists now :)
