### ISSUE TITLE
Missing '#include <stdlib.h>'; 'abort' must be declared before it is used

### ISSUE THREAD

**Issue by mauliknshah** [vapor/fluent-postgres-driver#177]
### To Reproduce

1. Create a new Project.
2. Add Fluent-Postgres-Drivers dependency using https://github.com/vapor/fluent-postgres-driver.git URL.
3. Compile.

### Expected behavior

Only one error as stated in the first line.

### Environment

Fluent-Postgres-Driver Version: 2.1.0 - (Exact or Next Major)
Swift-Nio-SSL version: 2.10.0 (Not added independently)
XCode Version: 11.7 or higher(Same error with XCode 12.3 Beta)
macOS Version: 11.0.1 (Big Sur)
- Project does not use Vapor.

### Additional context
I know it's an NIO error, but I haven't added any NIO dependencies independently.

**Comment by 0xTim** [comment]
Do you have Macports installed? That tends to mess with include paths. And have you tried deleting your derived data and trying again?

**Comment by mauliknshah** [comment]
- No, I don't have MacPorts installed.  
- Yes, I did all those things. 

Also, I tried to create a new project from scratch with just Nio-ssl and Nio dependencies, which produced the same error. I have raised the issue with the Nio team, which you can find it here: [Bug: Missing '#include <stdlib.h>'; 'abort' must be declared before it is used #259](https://github.com/apple/swift-nio-ssl/issues/259).

**Comment by 0xTim** [comment]
Ok, I'll close this issue as it looks deeper than anything we can help with here and unrelated to Vapor
