### ISSUE TITLE
debug logging no longer shows the RAW SQL

### ISSUE THREAD

**Issue by jeffreyrlewis** [vapor/fluent-postgres-driver#181]
### Describe the bug

In version 1.4.4 and earlier, with debug logging turned on, you would see the raw SQL in the logs.  In the current version you only get an abstracted representation of the query, which isn't helpful for sorting out subtle SQL problems.

### To Reproduce

Set LOG_LEVEL=debug and run any query.  I currently get log message like:
[ DEBUG ] query read courses filters=[courses[slug] = "en-ast-main"]

I don't believe there's anything special or unusual in my configuration, but let me know if I need to supply any details.

### Expected behavior

With 1.4.4, I get in addition to the above, the much more useful:
[ DEBUG ] SELECT "courses"."id" AS "courses_id", "courses"."name" AS "courses_name", "courses"."slug" AS "courses_slug", "courses"."source_language_id" AS "courses_source_language_id", "courses"."target_language_id" AS "courses_target_language_id", "courses"."creator_id" AS "courses_creator_id", "courses"."seed_set_id" AS "courses_seed_set_id", "courses"."script_status" AS "courses_script_status", "courses"."reverse_translation" AS "courses_reverse_translation", "courses"."preborg" AS "courses_preborg", "courses"."created_at" AS "courses_created_at", "courses"."updated_at" AS "courses_updated_at" FROM "courses" WHERE "courses"."slug" = $1 ["en-ast-main"]

This is what I expect to see.

### Environment

* Vapor Framework version: 4.45.6
* Vapor Toolbox version: 18.3.2
* OS version: Mac OS 11.4

**Comment by 0xTim** [comment]
Transferring here as this is where it should be solved. Resolved by #180
