### ISSUE TITLE
DatabaseConfigurationFactory build error in 2.7.0

### ISSUE THREAD

**Issue by rausnitz** [vapor/fluent-postgres-driver#211]
### Describe the bug

Starting in 2.7.0, the following code no longer builds for me:
```
let _ = DatabaseConfigurationFactory.postgres(
    configuration: PostgresConfiguration(url: "")!,
    maxConnectionsPerEventLoop: 1,
    connectionPoolTimeout: .seconds(30),
    sqlLogLevel: .info
)
```

The build error is:
```
cannot convert value of type 'PostgresConfiguration' to expected argument type 'SQLPostgresConfiguration'
```

### To Reproduce

Paste in the code example above, using version 2.7.0 of this package.

### Expected behavior

The code would build.

### Environment

Tested on macOS and Linux.

### Additional context

I haven't looked into the cause yet. I'll share a workaround as soon as I have a chance to make one, but ideally the code example above would still build after updating, and maybe a new patch could address that.

**Comment by rausnitz** [comment]
It has the same error.

**Comment by gwynne** [comment]
My fault, sorry 🤦‍♀️ I'll put up a PR to fix this shortly.
