### ISSUE TITLE
Feature Request: Add support for case-insensitive collation (CITEXT) and/or lowercase indices

### ISSUE THREAD

**Issue by MrMage** [vapor/fluent-postgres-driver#62]
When e.g. searching for an email address in a user database, we'd want fast case-insensitive searches for email addresses and enforce uniqueness of lowercased email addresses.

For this, we could use the [`CITEXT`](https://www.postgresql.org/docs/9.6/static/citext.html) type,  but would need a way to specify it when creating a Fluent model. I recall a discussion about using a custom wrapper type this for custom SQL types, but can't find it. Essentially we could have a `CaseInsensitiveString` wrapping `String` to indicate that `CITEXT` should be used when creating the column. Is there an example of another type that does something similar (using a custom SQL type) already as a "sample" implementation?

Alternatively, we could create a lowercase index like `CREATE UNIQUE INDEX unique_username_on_users ON users (lower(username));`, but for that we'd need a way to specify lowercase conversions in fluent filters, for example (the `.lower` parts are the tricky ones, because they'd need to be passed to SQL):

```
try User
	.query(on: connection)
	.filter(\User.email.lower == emailAddress.lower)
	.first()
```

Also, I'm not sure how we'd best query that. Or should we just run custom SQL for that? If so, I assume we'd need to run this outside the schema creator in a separate statement?

**Comment by Juice805** [comment]
Currently (1.0.0) `.custom("CITEXT")` is working for me

**Comment by brblakley** [comment]
@Juice805 Would you please point me in the right direction for where/how to use `.custom("CITEXT")`?

**Comment by tanner0101** [comment]
This section of the docs goes over using `.custom` with Fluent 4: https://docs.vapor.codes/4.0/fluent/advanced/#sql-custom

Closing this issue in favor of https://github.com/vapor/fluent-kit/issues/76, track there.

**Comment by jakestrickler** [comment]
For anyone discovering this late and wondering how to use the `CITEXT` type in a bit more detail, here's how I was able to solve it:

```
struct CreateUser: AsyncMigration {
    func prepare(on database: Database) async throws {
        if let sqlDB = database as? SQLDatabase {
            try await sqlDB.raw("CREATE EXTENSION citext;").run() // 1
        }

        try await database.schema("users")
            .id()
            .field("username", .custom("CITEXT"), .required) // 2
            ... other fields
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("users").delete()
    }
}
```

1. You first need to enable the CITEXT extension by executing the SQL for it or else your app will crash in the migration.
2. You can then use `.custom("CITEXT")` as the data type for your fields.

**Comment by benblakely** [comment]
@jakestrickler Thanks for posting the migration. That helped me out. Now I’m trying to figure out how to correctly use a citext column in a query filter. I’ve tried with something like this:

```
let user = try await User.query(on: database)
    .filter(\.$username == someUsername)
    .first()
```

But that doesn’t seem to do a case insensitive search. For example, if `someUsername` is `bob` and there’s a user already with the username of `Bob`, that user won’t be returned. Looking around a bit, I take it the problem has something to do with bindings. For example, this raw query behaves the same as the above:

```
let sqlDatabase = database as! SQLDatabase
let user = try await sqlDatabase.raw("select * from users where username = \(bind: someUsername)")
    .first(decoding: User.self)
```

But replacing `\(bind: someUsername)` with `\(raw: someUsername)` works (i.e., does a case insensitive search) but of course isn’t a real solution since it doesn’t protect against SQL injection.

Any ideas what the right way to do this is?

**Comment by JawadHF** [comment]
Explicitly casting it to `citext` when querying should work

```swift
let user = try await User.query(on: database)
    .filter(.sql(embed: "username = \(bind: someUsername)::citext"))
    .first()
```
