### ISSUE TITLE
Add support default value when adding new columns to table

### ISSUE THREAD

**Issue by kimdv** [vapor/fluent-postgres-driver#88]
Right now the [documentation](https://docs.vapor.codes/3.0/fluent/migrations/#updating-a-schema) don't say anything about adding default value when adding `mass` to `Galaxy`
Ass `mass` not is optional this will fail. 

Is there a way to add default value without writing a raw query?

**Comment by MrMage** [comment]
Unrelated to the feature request: be aware that adding a non-null column to a Postgres will rewrite the entire table (and lock it for the duration of that process). That can potentially take very long and bring your service down.

**Comment by tanner0101** [comment]
Closing in favor of https://github.com/vapor/fluent-kit/issues/324, thanks. For now, the best way to do this in Fluent 4 is with custom SQL: https://docs.vapor.codes/4.0/fluent/advanced/#sql

**Comment by xiao99xiao** [comment]
@tanner0101 Pardon me if this is not the place to ask, but could you give an example on how to add a `.required` property in a Migration `func prepare(on database: Database) -> EventLoopFuture<Void>` method when the database is not empty?
Thank you!

**Comment by zastrozzi** [comment]
@xiao99xiao proceed with caution but this is how I managed to set a required field for a Postgres DB:

```
struct MakeEnduserDateOfBirthRequiredMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        if let db = database as? PostgresDatabase {
            return db.simpleQuery("""
                ALTER TABLE "public"."endusers" ALTER COLUMN "date_of_birth" SET NOT NULL;
            """)
                .flatMap { _ in
                    return database.eventLoop.future()
                }
        } else {
            fatalError()
        }
    }
    
    func revert(on database: Database) -> EventLoopFuture<Void> {
        if let db = database as? PostgresDatabase {
            return db.simpleQuery("""
                ALTER TABLE "public"."endusers" ALTER COLUMN "date_of_birth" DROP NOT NULL;
            """)
                .flatMap { _ in
                    return database.eventLoop.future()
                }
        } else {
            fatalError()
        }
    }
}

```

**Comment by xiao99xiao** [comment]
@zastrozzi Great work! Many thanks!!
