### ISSUE TITLE
Join on tables with different enum fields with same name can cause a crash

### ISSUE THREAD

**Issue by FredericRuaudel** [vapor/fluent-postgres-driver#94]
FluentPostgreSQL version 1.0.0
PostgreSQL version 1.0.1
Vapor Core version: 3.4.2
_(see `Package.resolved` in joined example project for other module versions)_

I've recently stumble upon a bug while joining two tables that both have a `PostgreSQLEnum` field with the same name. And it causes a weird bug that was either:

- succeeds 
- crashing with `NIO-ELT-#1 (5): EXC_BAD_ACCESS` error
- crashing with `malloc: *** error for object 0x10383c710: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`
- throwing an error: `failed: caught error: The data couldn’t be read because it isn’t in the correct format.`
- throwing an error: `DecodingError.dataCorrupted: Cannot initialize AttachmentStatus from invalid String value done` (in the case of the attached sample project)

usually, it crashes half of the times and succeeds the other half with a perfect 1 for 1 rate

So to show the bug, I've created a simple sample project based on Todo template (see attached zip) with this simple DB schema to show the problem. You need to create a PG database named `joinenumbug` to make it runs and runs the tests of the app to get the bug.

We have a `Todo` table with a `status` field of type `Enum TodoStatus` and a `Attachment` table with also a `status` field but of another type `Enum AttachmentStatus` and they are linked via the `Todo`'s `attachmentId` foreignKey.

![schema_bugenum](https://user-images.githubusercontent.com/3808140/44861252-6f68eb00-ac78-11e8-80e9-20cd70bfb2a1.png)

So when I perform a join between this two tables, the result has two columns with the same name but with different data types inside:

![2018-08-30 at 17 29](https://user-images.githubusercontent.com/3808140/44862115-5103ef00-ac7a-11e8-89e5-a668e00e72b6.png)

and it confuses the decoder which is trying to pass all the status values to the `RawRepresentable` decodable `init` method and as the value doesn't matches any value, it throws an error in the best scenario

You can also see that clearly if you redefined the decodable `init` for the enum like this:

```swift
extension AttachmentStatus {
    public init?(rawValue: String) {
        print("############### --- \(rawValue)")
        if (rawValue == "new") {
            self = .new
        }
        else if (rawValue == "old") {
            self = .old
        }
        else {
            return nil
        }
    }
}
```

it will display:

```
############### --- old
############### --- new
############### --- done
############### --- doing
```

showing the problem.

The only workaround I've found is to rename one of the two fields with a different name but it's not a really satisfying solution 😉 

Hope you can help! 

Thanks in advance!

[JoinEnumBug.zip](https://github.com/vapor/fluent-postgresql/files/2336744/JoinEnumBug.zip)

**Comment by tanner0101** [comment]
This was happening because Postgres' table name cache is outdated and it is unable to resolve the difference between the two columns.  After running migrations you should call:
```swift
try! app.requestCachedConnection(to: .psql).wait()
```
This will reload postgres' table name cache allowing both `status` fields to be distinguishable.
