### ISSUE TITLE
Support DELETE IF EXISTS, CASCADE for schema

### ISSUE THREAD

**Issue by mura-admin** [vapor/fluent-postgres-driver#95]
This is useful for fast iteration on Schema models where you want to quickly replace an existing Schema with an updated one and have scripted a complete wipe and recreate on each iteration. 

CREATE IF NOT EXISTS would also be useful.

**Comment by tanner0101** [comment]
Fluent 4 has support for create if not exists with the `ignoreExisting()` method. Tracking deletion if exists here: https://github.com/vapor/fluent-kit/issues/325
